SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS PARAGRAPH;
CREATE TABLE PARAGRAPH (
    ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    CONTENT TEXT NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS IMAGE;
CREATE TABLE IMAGE (
    ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    DATA BLOB NOT NULL COMMENT 'Raw image data',
    ALT VARCHAR(20) NOT NULL COMMENT "HTML 'alt' field",
    CAPTION VARCHAR(50) NULL COMMENT 'Short description'
) ENGINE=INNODB;

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
    ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    
    NAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    PHONE VARCHAR(15) NULL,
    GENDER ENUM('M','F','O') NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS ABOUT;
CREATE TABLE ABOUT (
    ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS ABOUT_PARAGRAPH;
CREATE TABLE ABOUT_PARAGRAPH (
    ABOUT_ID SMALLINT UNSIGNED NOT NULL,
    PARAGRAPH_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (ABOUT_ID, PARAGRAPH_ID),
    FOREIGN KEY (ABOUT_ID) REFERENCES ABOUT(ID),
    FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH(ID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS ABOUT_IMAGE;
CREATE TABLE ABOUT_IMAGE (
    ABOUT_ID SMALLINT UNSIGNED NOT NULL,
    IMAGE_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (ABOUT_ID, IMAGE_ID),
    FOREIGN KEY (ABOUT_ID) REFERENCES ABOUT(ID),
    FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)
) ENGINE=INNODB;
DROP TABLE IF EXISTS HISTORY;
CREATE TABLE HISTORY (
    ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    TITLE VARCHAR(50) NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS HISTORY_PARAGRAPH;
CREATE TABLE HISTORY_PARAGRAPH (
    HISTORY_ID SMALLINT UNSIGNED NOT NULL,
    PARAGRAPH_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (HISTORY_ID, PARAGRAPH_ID),
    FOREIGN KEY (HISTORY_ID) REFERENCES HISTORY(ID),
    FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH(ID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS HISTORY_IMAGE;
CREATE TABLE HISTORY_IMAGE (
    HISTORY_ID SMALLINT UNSIGNED NOT NULL,
    IMAGE_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (HISTORY_ID, IMAGE_ID),
    FOREIGN KEY (HISTORY_ID) REFERENCES HISTORY(ID),
    FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS NEWS;
CREATE TABLE NEWS (
    ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    TITLE VARCHAR(50) NOT NULL,
    SUMMMARY TEXT NOT NULL COMMENT 'Short insight'
) ENGINE=INNODB;

DROP TABLE IF EXISTS NEWS_PARAGRAPH;
CREATE TABLE NEWS_PARAGRAPH (
    NEWS_ID SMALLINT UNSIGNED NOT NULL,
    PARAGRAPH_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (NEWS_ID, PARAGRAPH_ID),
    FOREIGN KEY (NEWS_ID) REFERENCES NEWS(ID),
    FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH(ID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS NEWS_IMAGE;
CREATE TABLE NEWS_IMAGE (
    NEWS_ID SMALLINT UNSIGNED NOT NULL,
    IMAGE_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (NEWS_ID, IMAGE_ID),
    FOREIGN KEY (NEWS_ID) REFERENCES NEWS(ID),
    FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS NEWS_PERSON;
CREATE TABLE NEWS_PERSON (
    NEWS_ID SMALLINT UNSIGNED NOT NULL,
    PERSON_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (NEWS_ID, PERSON_ID),
    FOREIGN KEY (NEWS_ID) REFERENCES NEWS(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
) ENGINE=INNODB COMMENT="The article's author";

DROP TABLE IF EXISTS FIGHT;
CREATE TABLE FIGHT (
    ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    TITLE VARCHAR(50) NOT NULL,
    SUMMMARY TEXT NOT NULL COMMENT 'Short insight'
) ENGINE=INNODB;

DROP TABLE IF EXISTS FIGHT_PARAGRAPH;
CREATE TABLE FIGHT_PARAGRAPH (
    FIGHT_ID SMALLINT UNSIGNED NOT NULL,
    PARAGRAPH_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (FIGHT_ID, PARAGRAPH_ID),
    FOREIGN KEY (FIGHT_ID) REFERENCES FIGHT(ID),
    FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH(ID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS FIGHT_IMAGE;
CREATE TABLE FIGHT_IMAGE (
    FIGHT_ID SMALLINT UNSIGNED NOT NULL,
    IMAGE_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (FIGHT_ID, IMAGE_ID),
    FOREIGN KEY (FIGHT_ID) REFERENCES FIGHT(ID),
    FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS FIGHT_PERSON;
CREATE TABLE FIGHT_PERSON (
    FIGHT_ID SMALLINT UNSIGNED NOT NULL,
    PERSON_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (FIGHT_ID, PERSON_ID),
    FOREIGN KEY (FIGHT_ID) REFERENCES FIGHT(ID),
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
) ENGINE=INNODB COMMENT="The fight's referent";

DROP TABLE IF EXISTS COUNTRY;
CREATE TABLE COUNTRY (
    ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    NAME VARCHAR(100) NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS COUNTRY_IMAGE;
CREATE TABLE COUNTRY_IMAGE (
    COUNTRY_ID SMALLINT UNSIGNED NOT NULL,
    IMAGE_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (COUNTRY_ID, IMAGE_ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID),
    FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)
) ENGINE=INNODB COMMENT="The country's flag";

DROP TABLE IF EXISTS ENCYCLOPEDIA;
CREATE TABLE ENCYCLOPEDIA (
    ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    NAME VARCHAR(100) NOT NULL,
    SPECIES VARCHAR(100) NULL,
    SIZE_MIN TINYINT UNSIGNED NULL,
    SIZE_MAX TINYINT UNSIGNED NULL,
    WEIGHT TINYINT UNSIGNED NULL,
    DESCRIPTION TEXT NOT NULL,
    HABITAT VARCHAR(100) NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS ENCYCLOPEDIA_IMAGE;
CREATE TABLE ENCYCLOPEDIA_IMAGE (
    ENCYCLOPEDIA_ID SMALLINT UNSIGNED NOT NULL,
    IMAGE_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (ENCYCLOPEDIA_ID, IMAGE_ID),
    FOREIGN KEY (ENCYCLOPEDIA_ID) REFERENCES ENCYCLOPEDIA(ID),
    FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS ENCYCLOPEDIA_PARAGRAPH_SOURCE;
CREATE TABLE ENCYCLOPEDIA_PARAGRAPH_SOURCE (
    ENCYCLOPEDIA_ID SMALLINT UNSIGNED NOT NULL,
    PARAGRAPH_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (ENCYCLOPEDIA_ID, PARAGRAPH_ID),
    FOREIGN KEY (ENCYCLOPEDIA_ID) REFERENCES ENCYCLOPEDIA(ID),
    FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH(ID)
) ENGINE=INNODB COMMENT="Encyclopedia's entry's sources";

DROP TABLE IF EXISTS ENCYCLOPEDIA_PARAGRAPH_TRIVIA;
CREATE TABLE ENCYCLOPEDIA_PARAGRAPH_TRIVIA (
    ENCYCLOPEDIA_ID SMALLINT UNSIGNED NOT NULL,
    PARAGRAPH_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (ENCYCLOPEDIA_ID, PARAGRAPH_ID),
    FOREIGN KEY (ENCYCLOPEDIA_ID) REFERENCES ENCYCLOPEDIA(ID),
    FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH(ID)
) ENGINE=INNODB COMMENT="Some encyclopedia's entry's trivia";

DROP TABLE IF EXISTS ENCYCLOPEDIA_COUNTRY;
CREATE TABLE ENCYCLOPEDIA_COUNTRY (
    ENCYCLOPEDIA_ID SMALLINT UNSIGNED NOT NULL,
    COUNTRY_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY (ENCYCLOPEDIA_ID, COUNTRY_ID),
    FOREIGN KEY (ENCYCLOPEDIA_ID) REFERENCES ENCYCLOPEDIA(ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID)
) ENGINE=INNODB;

SET FOREIGN_KEY_CHECKS=1;