# USE ONLY TO PREPARE A TEST DATABASE

# Minimal about: 1 paragraph, 0 image (ID 1)

INSERT INTO ABOUT (ID) VALUES (1);

INSERT INTO PARAGRAPH (ID, CONTENT) 
VALUES (1, 'About test 1');

INSERT INTO ABOUT_PARAGRAPH (ABOUT_ID, PARAGRAPH_ID)
VALUES (1, 1);

# Small about: 1 paragraph, 1 image (ID 2)

INSERT INTO ABOUT (ID) VALUES (2);

INSERT INTO IMAGE(ID, DATA, ALT)
VALUES(1, 0, 'test-small-about');

INSERT INTO PARAGRAPH (ID, CONTENT) 
VALUES (1, 'About test 2');

INSERT INTO ABOUT_PARAGRAPH (ABOUT_ID, PARAGRAPH_ID)
VALUES (2, 2);

INSERT INTO ABOUT_IMAGE (ABOUT_ID, IMAGE_ID)
VALUES (2, 1);

# Minimal country : 1 image (ID 1)

INSERT INTO COUNTRY(ID, NAME)
VALUES (1, 'Minimal country')

INSERT INTO IMAGE(ID, DATA, ALT)
VALUES (2, 0, 'test-minimal-country')

INSERT INTO COUNTRY_IMAGE (COUNTRY_ID, IMAGE_ID)
VALUES (1, 2)
